/* 
 * swdiag_linux_rpc_thread.c
 *
 * Copyright (c) 2007-2009 Cisco Systems Inc.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * Multithreaded HA Diagnostics server
 *
 * Requires two threads, one for servicing RPC's and one for HA Diags
 * itself.
 *
 * NOTE: To be replaced with something more generic across OS's, plus
 *       take into account the proposed new network API.
 */

#include <pthread.h>
#include <rpc/pmap_clnt.h>
#include "swdiag_unix_clients.h"
#include "swdiag_unix_rpc.h"

/*
 * Import RPC declarations from the autogenerated RPC srv file.
 */
void swdiag_remote_master_protocol_1(struct svc_req *rqstp, 
                                    register SVCXPRT *transp);

void swdiag_remote_slave_protocol_1(struct svc_req *rqstp, 
                                   register SVCXPRT *transp);

void *swdiag_rpc_thread (void *thread_context)
{
    swdiag_unix_info_t *swdiag_info = thread_context;
    SVCXPRT *transp;

    transp = svctcp_create(RPC_ANYSOCK, 0, 0);

    if (!transp) {
        fprintf(stderr, "Can not allocate a TCP port for RPC Server\n");
        exit(1);
    }

    if (swdiag_info->master) {
        /*
         * Register the RPC Server for being a master
         */
        pmap_unset(SWDIAG_REMOTE_MASTER_PROTOCOL,
                   SWDIAG_MASTER_PROTOCOL_V1);

        if (!svc_register(transp, 
                          SWDIAG_REMOTE_MASTER_PROTOCOL,
                          SWDIAG_MASTER_PROTOCOL_V1,
                          swdiag_remote_master_protocol_1,
                          IPPROTO_TCP)) {
            fprintf(stderr, "Unable to register master RPC protocol\n");
        }

    } else {
        /*
         * Register the RPC Server for being a slave using the RPC
         * instance provided in the swdiag_info.
         */  
        pmap_unset(swdiag_info->rpc_instance, 
                   SWDIAG_SLAVE_PROTOCOL_V1);

        if (!svc_register(transp, 
                          swdiag_info->rpc_instance, 
                          SWDIAG_SLAVE_PROTOCOL_V1,
                          swdiag_remote_slave_protocol_1,
                          IPPROTO_TCP)) {
            fprintf(stderr, "Unable to register slave RPC protocol\n");
        } 
    }

    /*
     * Block and handle the incoming RPC requests on this thread
     */
    svc_run();
    pthread_exit(NULL);
    return(NULL);
}
