/* 
 * swdiag_sunos_rpc_thread.c
 *
 * Copyright (c) 2007-2009 Cisco Systems Inc.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * Multithreaded HA Diagnostics server
 *
 * Requires two threads, one for servicing RPC's and one for Diags
 * itself.
 */

#include <stdlib.h>
#include <pthread.h>
#include "swdiag_unix_clients.h"
#include "swdiag_unix_rpc.h"

/*
 * Import RPC declarations from the autogenerated RPC srv file.
 */
void swdiag_remote_master_protocol_1(struct svc_req *rqstp, 
                                    register SVCXPRT *transp);

void swdiag_remote_slave_protocol_1(struct svc_req *rqstp, 
                                   register SVCXPRT *transp);

void *swdiag_rpc_thread (void *thread_context)
{
    swdiag_unix_info_t *swdiag_info = thread_context;

    if (swdiag_info->master) {
        /*
         * Register the RPC Server for being a master
         */
        if (!svc_create(swdiag_remote_master_protocol_1, 
                        SWDIAG_REMOTE_MASTER_PROTOCOL, 
                        SWDIAG_MASTER_PROTOCOL_V1, "tcp")) {
            fprintf(stderr, "Unable to register master RPC protocol\n");
            exit(1);
        }
    } else {
        /*
         * Register the RPC Server for being a slave using the RPC
         * instance provided in the swdiag_info.
         */
        if (!svc_create(swdiag_remote_slave_protocol_1, 
                        swdiag_info->rpc_instance, 
                        SWDIAG_SLAVE_PROTOCOL_V1, "tcp")) {
            fprintf(stderr, "Unable to register slave RPC protocol 0x%x\n",
                    swdiag_info->rpc_instance);
            exit(1);
        }
    }

    /*
     * Block and handle the incoming RPC requests on this thread
     */
    svc_run();
    pthread_exit(NULL);
    return(NULL);
}
